# Generated by Django 5.2.7 on 2025-11-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="tg_nick",
        ),
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID чата в ТГ",
                max_length=50,
                null=True,
                verbose_name="ID чата в ТГ",
            ),
        ),
    ]
