# Generated by Django 5.2.7 on 2025-11-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ("-action",),
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
